version: "2"
services:
  web:
    build: ./web/
    links:
      - data
    ports:
      - 3000:3000
    volumes:
      - .:/home/todo-backend-express
    depends_on:
      - data
  data:
    image: mongo
    ports:
    - 27017:27017
